### PR TITLE
No api calls

### PR DESCRIPTION
**Pull request by frontierpsycho**

### CODE REVIEW

**Comment by frontierpsycho** [comment]
Don't merge this! It's not complete and tested.

**Comment by thiderman** [comment]
Is this complete yet? :)

**Comment by frontierpsycho** [comment]
No. Do you think it's important? Should I continue?

**Comment by thiderman** [comment]
In one sense I like it, but I'm not sure if it's an improvement we really need to make, and furthermore the use of `$broadcast` is deprecated in Vue 2.0. So, implementing this would mean that #52 would be trickier!

What do you think? What's the big gain for this?

**Comment by frontierpsycho** [comment]
I think it would be nice to have neater front-end code, it would potentially save us from insidious bugs that are either already there, or will be in the future. But I think a refactoring can be done when migrating to Vue 2.0, and no effort should be expended here. 

Yesterday and today I've been trying to think of a better way to use the WebSocket state in components. I have some ideas, I'll try them out at some point. 

In the meantime, I'll abandon this and keep it as reference if I take on migration to Vue 2.0. Make sense?

**Comment by thiderman** [comment]
Yes, that makes perfect sense!

You may close this at your own discretion then! :)

**Pull request closed without merging**
