### PR TITLE
Disable end round button when appropriate.

### LINKED ISSUE #73: Only show End Round button for judges when scores have been entered

### PR DESCRIPTION
**Pull request by frontierpsycho**
Closes #73.

### CODE REVIEW

**Comment by frontierpsycho** [comment]
Yup, tried it and it worked both with kills and with suicides/shots. Anything on the console?

**Comment by kallekrantz** [comment]
Hey, updated your PR with some additional stuff for ensuring that the end round button is also disabled when someone reached the end point of the game, hopefully I didn't run over any of your changes (please shout if I did!)

FYI: I'll rebase from master now, so there might be some weirdness on next pull for you

**Comment by kallekrantz** [comment]
Hello, back again (to cause a commotion)!

Rebased successfully, everything seems to be working, found one issue when doing the "early quit" though: 

When giving the winning player a negative point upon winning, It still allowed me to finish the round, even though the player did not have 10 points anymore (9 + 1 - 1 points to be exact).

Probably something small, but didn't wanna merge it yet.

**Comment by frontierpsycho** [comment]
I pulled, and your commit works, and was necessary! I didn't think of that. Thanks.

Hm, I see your point about finishing the round at 9 points, but I think it's a Good Idea (TM) to not try to be overly smart about activating and deactivating the button, or else we'll end up in situation where the judges need to end a round and they can't because of the overly smart logic having deactivated the button.

The logic of activating the button only after 3 ups/downs and not fiddling with it after that, basically just makes sure the judges don't accidentally click the End round button before they should.

On the other hand, if they make a mistake, they can always tap all player usernames and reset all players (which is a great feature that I'm not sure has been communicated).

I'd say this is mergable, if it works for Lowe as well. What do you think?

**Comment by thiderman** [comment]
This has been obsoleted by other code.

**Pull request closed without merging**
